### ISSUE TITLE
Multiple Launch files is not currently support in testing

### ISSUE THREAD

**Issue by joshuamorton** [gtagency/buzzmobile#149]
Currently, multiple trying to use `rostest_utils.with_launch_file` for multiple launch files will cause silent errors.

**Comment by irapha** [comment]
TODO is here: https://github.com/gtagency/buzzmobile/pull/121/files#diff-0b78e1468bd4bce4d2aec5aea89987beR49

**Comment by irapha** [comment]
@joshuamorton correct me if I'm wrong but isn't this almost fixed with #180 too?

(It's not high priority so please don't {put it in the same PR/worry about it} if it's not already being fixed there)

**Comment by joshuamorton** [comment]
I don't think I do much to address this.

The issue is still that the @with_launch_file decorator will override parent launch files.

**Comment by irapha** [comment]
Oh ok. Honestly I'm considering closing this issue until we actually express a need for loading multiple launch files...

**Comment by joshuamorton** [comment]
Given that afaik we can have launch files import other launch files, I
don't see a strong need for it either.
